<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegistrationSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('registrations')->insert([
            [
                'psa_id'           => '3114',
                'prc_number'       => 11234124,
                'last_name'        => 'CRISTI',
                'first_name'       => 'MARIA VANESSA',
                'middle_name'      => 'A.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'TEST',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => null,
                'status'           => 'Approved',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 00:03:10',
                'updated_at'       => '2025-12-17 00:03:10',
            ],
            [
                'psa_id'           => '3115',
                'prc_number'       => 11234124,
                'last_name'        => 'ELLICA',
                'first_name'       => 'SYD',
                'middle_name'      => 'A.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'TEST',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'TM',
                'discount_id'      => 'No discount',
                'proof_payment'    => null,
                'status'           => 'Approved',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 00:04:04',
                'updated_at'       => '2025-12-17 00:04:04',
            ],
            [
                'psa_id'           => '3115',
                'prc_number'       => 11234124,
                'last_name'        => 'ELLICA',
                'first_name'       => 'SYD',
                'middle_name'      => 'A.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'TEST',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'TM',
                'discount_id'      => 'No discount',
                'proof_payment'    => null,
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 00:04:17',
                'updated_at'       => '2025-12-17 00:04:17',
            ],
            [
                'psa_id'           => '3114',
                'prc_number'       => 23131,
                'last_name'        => 'CRISTI',
                'first_name'       => 'MARIA VANESSA',
                'middle_name'      => 'A.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'TEST',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => null,
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 01:04:45',
                'updated_at'       => '2025-12-17 01:04:45',
            ],
            [
                'psa_id'           => '2314',
                'prc_number'       => 123,
                'last_name'        => 'MARZO-MADDATU',
                'first_name'       => 'EUNICE CAROLL',
                'middle_name'      => 'C.',
                'hospital_name'    => 'asd',
                'hospital_address' => 'asd',
                'email'            => 'qwe@awe1',
                'contact_number'   => '1231',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '2314 MARZO-MADDATU - Proof of Payment 121825 - 022537.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 18:25:37',
                'updated_at'       => '2025-12-17 18:25:37',
            ],
            [
                'psa_id'           => '3116',
                'prc_number'       => 123,
                'last_name'        => 'ENRIQUEZ, JR.',
                'first_name'       => 'RODOLFO',
                'middle_name'      => 'B.',
                'hospital_name'    => 'asd',
                'hospital_address' => 'asd',
                'email'            => 'asda@asd',
                'contact_number'   => '1231',
                'membership'       => 'RM',
                'discount_id'      => '3116 ENRIQUEZ, JR. - pwd_disc 121825 - 024327.heic',
                'proof_payment'    => '3116 ENRIQUEZ, JR. - Proof of Payment 121825 - 024327.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 18:43:27',
                'updated_at'       => '2025-12-17 18:43:27',
            ],
            [
                'psa_id'           => '0002',
                'prc_number'       => 123,
                'last_name'        => 'MANZANO-MANZON',
                'first_name'       => 'AMELIA JASMIN',
                'middle_name'      => 'C.',
                'hospital_name'    => 'asd',
                'hospital_address' => 'asd',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '0002 MANZANO-MANZON - Proof of Payment 121825 - 032303.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 19:23:03',
                'updated_at'       => '2025-12-17 19:23:03',
            ],
            [
                'psa_id'           => '0002',
                'prc_number'       => 123,
                'last_name'        => 'MANZANO-MANZON',
                'first_name'       => 'AMELIA JASMIN',
                'middle_name'      => 'C.',
                'hospital_name'    => 'asd',
                'hospital_address' => 'asd',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '0002 MANZANO-MANZON - Proof of Payment 121825 - 032317.heic',
                'status'           => 'Approved',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-17 19:23:17',
                'updated_at'       => '2025-12-17 19:23:17',
            ],
            [
                'psa_id'           => '2415',
                'prc_number'       => 123,
                'last_name'        => 'MADARANG',
                'first_name'       => 'MICHAEL RONALD',
                'middle_name'      => 'B.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'TEST',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '123',
                'membership'       => 'RM',
                'discount_id'      => '2415 MADARANG - pwd_disc 121925 - 022445.heic',
                'proof_payment'    => '2415 MADARANG - Proof of Payment 121925 - 022445.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-18 18:24:45',
                'updated_at'       => '2025-12-18 18:24:45',
            ],
            [
                'psa_id'           => '1658',
                'prc_number'       => 12313,
                'last_name'        => 'REYES',
                'first_name'       => 'YOLANDA',
                'middle_name'      => 'H.',
                'hospital_name'    => 'TEST',
                'hospital_address' => 'test',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '13213',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '1658 REYES - Proof of Payment 122225 - 021150.heic',
                'status'           => 'Approved',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-21 18:11:50',
                'updated_at'       => '2025-12-21 18:11:50',
            ],
            [
                'psa_id'           => '4123',
                'prc_number'       => 123123,
                'last_name'        => 'CABORNAY',
                'first_name'       => 'JAN BENARV',
                'middle_name'      => 'C.',
                'hospital_name'    => '123123',
                'hospital_address' => '13123',
                'email'            => 'pcreyes09@gmail.com',
                'contact_number'   => '123',
                'membership'       => 'RM',
                'discount_id'      => '4123 CABORNAY - pwd_disc 122525 - 030143.heic',
                'proof_payment'    => '4123 CABORNAY - Proof of Payment 122525 - 030143.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-24 19:01:43',
                'updated_at'       => '2025-12-24 19:01:43',
            ],
            [
                'psa_id'           => '1534',
                'prc_number'       => 1312,
                'last_name'        => 'PASTORAL',
                'first_name'       => 'GLORINIA',
                'middle_name'      => 'A.',
                'hospital_name'    => 'qwe',
                'hospital_address' => 'qwewq',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'RM',
                'discount_id'      => '1534-PASTORAL-senior_disc-122525 - 031619.heic',
                'proof_payment'    => '1534-PASTORAL-Proof_of_Payment-122525-031619.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-24 19:16:19',
                'updated_at'       => '2025-12-24 19:16:19',
            ],
            [
                'psa_id'           => '5123',
                'prc_number'       => 123123,
                'last_name'        => 'CRUZ',
                'first_name'       => 'AUDREY SHANNEN',
                'middle_name'      => 'I.',
                'hospital_name'    => '123123',
                'hospital_address' => '123123',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '12313',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '5123-CRUZ-Proof_of_Payment-122525-105101.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-25 14:51:01',
                'updated_at'       => '2025-12-25 14:51:01',
            ],
            [
                'psa_id'           => '5123',
                'prc_number'       => 123123,
                'last_name'        => 'CRUZ',
                'first_name'       => 'AUDREY SHANNEN',
                'middle_name'      => 'I.',
                'hospital_name'    => '123123',
                'hospital_address' => '123123',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '12313',
                'membership'       => 'RM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '5123-CRUZ-Proof_of_Payment-122525-105304.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-25 14:53:04',
                'updated_at'       => '2025-12-25 14:53:04',
            ],
            [
                'psa_id'           => '5632',
                'prc_number'       => 3232,
                'last_name'        => 'ANTONIO',
                'first_name'       => 'WILFRED',
                'middle_name'      => 'I.',
                'hospital_name'    => '123',
                'hospital_address' => '233',
                'email'            => 'pcrstorage09@gmail.com',
                'contact_number'   => '123123',
                'membership'       => 'TM',
                'discount_id'      => 'No discount',
                'proof_payment'    => '5632-ANTONIO-Proof_of_Payment-122525-105857.heic',
                'status'           => 'Pending',
                'country'          => 'Philippines',
                'created_at'       => '2025-12-25 14:58:57',
                'updated_at'       => '2025-12-25 14:58:57',
            ],
        ]);
    }
}